#
# Sera - OnePage Jekyll Theme
# Configuration File
#

# Information for compile
exclude: ["Gemfile", "README.md"]

# Sass configuration
sass:
  sass_dir: _scss

# Information for deploy
baseurl: ""

# the base hostname & protocol for your site
url: "http://localhost:4000"

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

####################################
###########   Plugins    ###########
####################################
plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: "archive"
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: Fides et Ratio
# Website language
lang: en-US
# Header Title
header-title: Human Intelligence (HI)
# Header Tagline
headter-tagline: Learned Truth

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: True Measurements
  url: https://s3.us-east-1.amazonaws.com/www.decision-machine.com/register-training.html

# Secondary Buttons
header-secondary-button:
  title: Data Dictionary
  url: https://fides-ratio.com/decision-machine/data-dictionary.html

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: mtempler@decision-machine.com

# Offer Banner Link
# Default link is a link to all Sera OnePage products
# banner-link: https://themeforest.net/collections/6069390-sera

####################################
######  Global Social Links   ######
####################################
youtube: "#"
pinterest: "#"
facebook: "#"
twitter: "#"
google-plus: "#"
vimeo: "#"

#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
about-widget:
  author-avatar: avatar-02.jpg
  author-name: MTR
  author-tagline: Blog Author
  author-info: Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies.
  author-social-links:
    youtube: "#"
    pinterest: "#"
    facebook: "#"
    twitter: "#"
    google-plus: "#"

#####################################
#############   About   #############
#####################################
about-title: Welcome to Fides et Ratio
about-description: At Fides et Ratio we hold that Human Intelligence (HI) is a gift from God.  And, from St. Thomas, that truth is the conformity of human intellect and thing.  AI as a Theory-of-Everything cannot be true, because it faces in the wrong direction and relies on untrue statistical assumptions.  By returning to the foundations of science, the science-of-counting accepts any time-series and returns scientific measurements, as deductive reality. 

#####################################
#############  Features  ############
#####################################
features-title: Features
features-description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante.

#
# Features
#
features:
  # Feature
  - title: Scientific Measurements
    description: For any time-series, a complete set of thermodynamics measurements is returned.  The total energy that enters or exits the environment can be measured, making the system non-mechanical..
    icon: pe-7s-vector

  # Feature
  - title: Transparent
    description: Pure measurement.  No Models or Model Biases, and, no Model Development Lifecycle.
    icon: pe-7s-help2

  # Feature
  - title: Inclusive
    description: Ease of use.  No theory required to operate effectively.
    icon: pe-7s-airplay

#####################################
############# Our Blog ##############
#####################################
blog-title: Our Blog
blog-description: Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.

#####################################
############  Portfolio  ############
#####################################
portfolio-title: Portfolio
portfolio-description: Maecenas tempus nec mi et placerat. Duis at odio vitae ex gravida volutpat. Nulla finibus aliquet diam ut eleifend. Mauris consequat interdum quam. Mauris dui sapien, efficitur et cursus id, molestie fringilla turpis.

#
# Portfolio Grid
#
portfolio-categories:
  [Websites, Logo, Graphic Design, Development, Video, Photography]
portfolio:
  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [Websites, Graphic Design]
    image: img-01.jpg
    url: "#"

  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [Graphic Design, Logo, Websites]
    image: img-02.jpg
    url: "#"

  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [Graphic Design, Logo, Photography]
    image: img-03.jpg
    url: "#"

  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [Websites, Video, Photography]
    image: img-04.jpg
    url: "#"

  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [Development, Logo]
    image: img-05.jpg
    url: "#"

  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [Development, Video]
    image: img-06.jpg
    url: "#"

  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [Websites, Graphic Design]
    image: img-07.jpg
    url: "#"

  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [Websites, Video]
    image: img-08.jpg
    url: "#"

  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [Photography, Logo]
    image: img-09.jpg
    url: "#"

#####################################
##########  Core Features  ##########
#####################################
core-title: Core Features
core-description: Duis at odio vitae ex gravida volutpat. Nulla finibus aliquet diam ut eleifend. Mauris consequat interdum quam. Mauris dui sapien, efficitur et cursus id, molestie fringilla turpis aliquet diam ut eleifend.

#
# Core Features Left
#
core-features-left:
  # Feature
  - name: Scientific Human Intelligence (HI)
    description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
    icon: pe-7s-light

  # Feature
  - name: Deductive
    description: No Models, No Model Building, No Model Biases.
    icon: pe-7s-drop

  # Feature
  - name: Universal, Vertical Independent
    description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
    icon: pe-7s-coffee

  # Feature
  - name: Generalizes Statistics to Probability Theory 
    description: Removes invalid statistical assumptions

#
# Core Features Right
#
core-features-right:
  # Feature
  - name: Transparent and Accountable
    description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
    icon: pe-7s-wine

  # Feature
  - name: Inclusion and Access
    description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
    icon: pe-7s-monitor

  # Feature
  - name: Graphic Design
    description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
    icon: pe-7s-crop

  # Feature
  - name: Photography
    description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
    icon: pe-7s-camera

#####################################
############   Contact   ############
#####################################
contact-title: Contact Us
contact-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat.

#####################################
#############   Footer   ############
#####################################
footer-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat.
footer-copyright-text: Ohkimur
footer-copyright-url: https://github.com/ohkimur
footer-copyright-year: 2021
