# Information for compile
exclude: ["Gemfile", "README.md"]

# Sass configuration
sass:
  sass_dir: _scss

# Information for deploy
baseurl: ""

# the base hostname & protocol for your site
url: "http://localhost:4000"

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

####################################
###########   Plugins    ###########
####################################
plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: "archive"
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: Fides et Ratio
# Website language
lang: en-US
# Header Title
header-title: Human Intelligence (HI)
# Header Tagline
headter-tagline: Learned Truth

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: True Measurements
  url: https://fides-ratio.com/decision-machine/register-training.html

# Secondary Buttons
header-secondary-button:
  title: Data Dictionary
  url: https://fides-ratio.com/decision-machine/data-dictionary.html

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: mtempler@decision-machine.com

# Offer Banner Link
# Default link is a link to all Sera OnePage products
# banner-link: https://themeforest.net/collections/6069390-sera

#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
about-widget:
  author-avatar: avatar-02.jpg
  author-name: MTR
  author-tagline: Blog Author
  author-info: Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies.
  author-social-links:
    youtube: "#"
    pinterest: "#"
    facebook: "#"
    twitter: "#"
    google-plus: "#"

#####################################
#############   About   #############
#####################################
about-title: Welcome to Fides et Ratio
about-description: R. Tagore writes, "we read the world wrong and say that it deceives us."  
We mistaken our interpretations and readings of reality for Reality itself.  The illusion is made up of projections, a priori assumptions, and judgements that are more or less inherited from others.  We apply these automatically and without concern for examination or verification that would help us to discover if the glass we use to read reality is really telling us anything about Reality, or, hides it from us.  It can be empirically shown that we are at present enclosed in an arrested perception of the world.  Notably, measurements of the world through time-series bluntly contradict statistical assumptions and local stationarity.  By returning to the foundations of science, the science-of-counting, Scientific Machine Learning provides a rigorous derivation for Machine Learning that generalizes statistics to probability theory, demonstrates that energy can enter and exit the system (is not mechanical), and can accept any time-series to return a complete set of scientific measurements as deductive Reality.

#####################################
#############  Features  ############
#####################################
features-title: Features
features-description: The science-of-counting is science when counting in units.  This is achieved by counting up to the last full measure, which ensures that multiple measurers, given the same unit of measure, will get the exact same measurement. Any leftover by definition is less than a full unit of measure, and is ignored.

#
# Features
#
features:
  # Feature
  - title: Scientific Measurements
    description: Scientific Machine Learning (SML) integrates the science-of-counting with time-series data to define deductive, combinatorial scientific measurements, including, exact discrete probability distributions, the energy entering or exiting the system, temperature, dissipation, and so on.  Scientific Machine Learning generates real-time, model-free, vertical independent measurements from time-series, also known as pure measurements.  
    icon: pe-7s-vector

  # Feature
  - title: Human Decisions
    description: Human decisions operate in the non-equilibrium reality measured by time-series.  Because human decisions can respond to external influences, control decisions are also human decisions.  Mechanical decisions, on the other hand, forbid external influences and assume that the statistical future is the same as the statistical past, equivalently, no energy is allowed to enter or exit.  Human decisions cannot be expressed as fixed-rule procedures on data.  
    icon: pe-7s-help2

  # Feature
  - title: Transparent, Accessible and Inclusive
    description: Mathematically transparent deductive measurements that are available for processing in the cloud.  No models and vertical agnostic.  Anybody can be a data-scientist by taking scientific measurements and thinking about their meaning.  Fides et Ratio will host global community discussions (github) and help to organize what is learned.
    icon: pe-7s-airplay

#####################################
############# Our Blog ##############
#####################################
blog-title: Our Blog
blog-description: Lessons learned and directions to explore.

#####################################
############  Portfolio  ############
#####################################
portfolio-title: Portfolio
portfolio-description: Maecenas tempus nec mi et placerat. Duis at odio vitae ex gravida volutpat. Nulla finibus aliquet diam ut eleifend. Mauris consequat interdum quam. Mauris dui sapien, efficitur et cursus id, molestie fringilla turpis.

#
# Portfolio Grid
#
portfolio-categories:
  [Websites, Logo, Graphic Design, Development, Video, Photography]
portfolio:
  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [Websites, Graphic Design]
    image: img-01.jpg
    url: "#"

  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [Graphic Design, Logo, Websites]
    image: img-02.jpg
    url: "#"

  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [Graphic Design, Logo, Photography]
    image: img-03.jpg
    url: "#"

  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [Websites, Video, Photography]
    image: img-04.jpg
    url: "#"

  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [Development, Logo]
    image: img-05.jpg
    url: "#"

  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [Development, Video]
    image: img-06.jpg
    url: "#"

  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [Websites, Graphic Design]
    image: img-07.jpg
    url: "#"

  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [Websites, Video]
    image: img-08.jpg
    url: "#"

  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [Photography, Logo]
    image: img-09.jpg
    url: "#"

#####################################
##########  Core Features  ##########
#####################################
core-title: Core Features
core-description: Duis at odio vitae ex gravida volutpat. Nulla finibus aliquet diam ut eleifend. Mauris consequat interdum quam. Mauris dui sapien, efficitur et cursus id, molestie fringilla turpis aliquet diam ut eleifend.

#
# Core Features Left
#
core-features-left:
  # Feature
  - name: Scientific Human Intelligence (HI)
    description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
    icon: pe-7s-light

  # Feature
  - name: Deductive
    description: No Models, No Model Building, No Model Biases.
    icon: pe-7s-drop

  # Feature
  - name: Universal, Vertical Independent
    description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
    icon: pe-7s-coffee

  # Feature
  - name: Generalizes Statistics to Probability Theory 
    description: Removes invalid statistical assumptions

#
# Core Features Right
#
core-features-right:
  # Feature
  - name: Transparent and Accountable
    description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
    icon: pe-7s-wine

  # Feature
  - name: Inclusion and Access
    description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
    icon: pe-7s-monitor

  # Feature
  - name: Graphic Design
    description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
    icon: pe-7s-crop

  # Feature
  - name: Photography
    description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
    icon: pe-7s-camera

#####################################
############   Contact   ############
#####################################
contact-title: Contact Us
contact-description: If participation in the community is your interest, visit our <a href="https://github.com/mtempler/mtempler.github.io/discussions">GitHub Discussions</a>.  Otherwise, please feel free to write to us below.

#####################################
#############   Footer   ############
#####################################
footer-quote: We read the world wrong and say that it deceives us.
footer-quote-author: Tagore
footer-copyright-text: Fides-et-Ratio
footer-copyright-url: https://github.com/mtempler
footer-copyright-year: 2026
